import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {History,Users,FileSpreadsheet,ClipboardCheck,LifeBuoy,UserRound,LogOut,Menu,ShieldCheck,Check,MapPin,ArrowRight,Settings,Search,Fingerprint} from 'lucide-react';
import {api,Field,Password,Button,Modal,Notice,dateNow,hours} from './ui';
import {People,preloadPeople} from './people';
import {Records,Management,Requests,Reports,Support,Profile,Chat,SettingsPage} from './pages';
import {QRAccess} from './qr';
import './style.css';
import {locate,warmLocation} from './location';

function App(){
 const [me,setMe]=useState(null),[punchInitial,setPunchInitial]=useState(null),[loading,setLoading]=useState(true),[page,setPage]=useState('Ponto'),[error,setError]=useState(''),[toast,setToast]=useState(''),[busy,setBusy]=useState(false),[nav,setNav]=useState(false),[chat,setChat]=useState(false),[passwordPrompt,setPasswordPrompt]=useState(false),[unread,setUnread]=useState({count:0,names:[]}),[messageNotice,setMessageNotice]=useState(false);
 const navCount=useRef(0);
 const timer=useRef(),generation=useRef(0),activeRuns=useRef(0),refreshing=useRef(false);
 const notify=text=>{setToast(text);clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),6500);};
 const run=async fn=>{activeRuns.current++;setBusy(true);setError('');try{return await fn();}catch(e){setError(e.message);window.dispatchEvent(new CustomEvent('ponto-error',{detail:e.message}));if(e.status===401){generation.current++;setMe(null);}return null;}finally{activeRuns.current--;setBusy(activeRuns.current>0);}};
 const refresh=async()=>{if(refreshing.current)return;refreshing.current=true;const version=generation.current;try{const r=await api('/me');if(version===generation.current){setMe(old=>JSON.stringify(old)===JSON.stringify(r.user)?old:r.user);if(r.punch)setPunchInitial(r.punch)}}catch(e){if(version===generation.current){if(e.status===401)setMe(null);else setError(e.message);}}finally{refreshing.current=false;setLoading(false);}};
 useEffect(()=>{refresh();},[]);
 useEffect(()=>{if(!me)return;let stopped=false,t;const poll=async()=>{if(document.visibilityState==='visible')await refresh();if(!stopped)t=setTimeout(poll,30000);};t=setTimeout(poll,30000);const visible=()=>{if(document.visibilityState==='visible')refresh();};document.addEventListener('visibilitychange',visible);return()=>{stopped=true;clearTimeout(t);document.removeEventListener('visibilitychange',visible);};},[me?.id]);
 const readMessages=async()=>{await api('/tickets/read',{});setUnread({count:0,names:[]})};
 const ctx={me,run,busy,notify,refresh};
 const change=p=>{setPage(p);setError('');setNav(false);if(p==='Atendimentos')run(readMessages);if(me?.temporary&&!passwordPrompt){navCount.current++;if(navCount.current>=2){navCount.current=0;setPasswordPrompt(true);}}};
 useEffect(()=>{if(me?.temporary)setPasswordPrompt(true);else setPasswordPrompt(false)},[me?.id,me?.temporary]);
 useEffect(()=>{if(!me)return;const timer=setTimeout(()=>{const paths=[],admin=['Administração','Diretoria','Suporte'].includes(me.role);if(admin){paths.push('/people','/today-events','/requests');preloadPeople().catch(()=>{})}if(me.role==='Suporte')paths.push('/tickets?management=true','/support/occurrences','/support/my-location');if(['Suporte','Diretoria'].includes(me.role))paths.push('/system/storage','/support/settings','/system/qr');Promise.allSettled(paths.map(path=>api(path)))},400);return()=>clearTimeout(timer)},[me?.id]);
 useEffect(()=>{if(me?.role!=='Suporte'||me.access_required)return;let active=true;const load=async show=>{try{const value=await api('/tickets/unread');if(active){setUnread(value);if(show&&value.count)setMessageNotice(true)}}catch{}};load(true);const timer=setInterval(()=>load(false),15000);return()=>{active=false;clearInterval(timer)}},[me?.id,me?.role,me?.access_required]);
 if(loading)return <div className="login-shell">Carregando…</div>;
 if(!me)return <><Login notify={notify} onLogin={(p,initial)=>{generation.current++;setMe(p);if(initial)setPunchInitial(initial);const back=sessionStorage.getItem('ponto_qr_return');if(back&&!p.access_required){sessionStorage.removeItem('ponto_qr_return');location.href=back;return}setPage(p.role==='Diretoria'?'Usuários':'Ponto');}} run={run} busy={busy}/>{error&&<div className="toast error" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}</>;
 if(me.access_required)return <AccessChoice me={me} busy={busy} run={run} choose={(user,punch)=>{setMe(user);setPunchInitial(punch);const back=sessionStorage.getItem('ponto_qr_return');if(back){sessionStorage.removeItem('ponto_qr_return');location.href=back;return}setPage(user.role==='Diretoria'?'Usuários':'Ponto')}}/>;
 const admin=['Administração','Diretoria','Suporte'].includes(me.role);
 const links=[[['Ponto',Fingerprint],['Meus Registros',History],['Meu Perfil',UserRound]],...(admin?[[['Usuários',Users],['Marcações',Search],['Excel',FileSpreadsheet],...(['Suporte','Diretoria'].includes(me.role)?[['Solicitações',ClipboardCheck]]:[]),...(me.role==='Suporte'?[['Atendimentos',LifeBuoy],['Central de Suporte',ShieldCheck]]:[])]]:[]),...(me.role!=='Suporte'?[[['Falar com Suporte',LifeBuoy]]]:[]),...(['Suporte','Diretoria'].includes(me.role)?[[['Configurações',Settings]]]:[])];
 return <div className="app"><aside className={nav?'sidebar open':'sidebar'}><div className="brand"><strong>Olá, {me.name.trim().split(/\s+/)[0]}</strong></div><nav>{links.map((group,g)=><React.Fragment key={g}>{g>0&&<hr/>}{group.map(([name,Icon])=><button key={name} className={page===name?'selected':''} onClick={()=>change(name)}>{Icon&&<Icon size={20}/>} <span>{name}</span>{name==='Atendimentos'&&unread.count>0&&<span className="nav-badge" aria-label={`${unread.count} mensagens pendentes`}>{unread.count}</span>}</button>)}</React.Fragment>)}</nav><div className="account"><span className="avatar">{me.name[0]}</span><div><strong>{me.name.split(' ')[0]}</strong><span>{me.role}</span></div><button className="icon" title="Sair" onClick={()=>run(async()=>{await api('/logout',{});generation.current++;setMe(null);})}><LogOut size={19}/></button></div></aside>{nav&&<button className="nav-shade" aria-label="Fechar menu" onClick={()=>setNav(false)}/>}
 <main className={page==='Excel'?'report-page':''}><header className={`page-head ${['Ponto','Meus Registros'].includes(page)?'titleless':''}`}><button className="mobile icon" aria-label="Abrir menu" onClick={()=>setNav(true)}><Menu/></button>{!['Ponto','Meus Registros'].includes(page)&&<h1>{page}</h1>}</header>{error&&<div className="inline-error" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}
 {page==='Ponto'&&<Punch {...ctx} initial={punchInitial} onSupport={me.role!=='Suporte'?()=>change('Falar com Suporte'):null}/>}{page==='Usuários'&&admin&&<People {...ctx}/>}{page==='Meus Registros'&&<Records key={page} {...ctx} administrative={false}/>} {page==='Marcações'&&admin&&<Management {...ctx}/>}{page==='Solicitações'&&<Requests {...ctx} admin={admin}/>}{page==='Excel'&&admin&&<Reports {...ctx}/>}{page==='Central de Suporte'&&me.role==='Suporte'&&<Support {...ctx}/>} {page==='Atendimentos'&&me.role==='Suporte'&&<Chat {...ctx} management/>} {page==='Meu Perfil'&&<Profile {...ctx}/>} {page==='Configurações'&&['Suporte','Diretoria'].includes(me.role)&&<SettingsPage {...ctx}/>}{page==='Falar com Suporte'&&me.role!=='Suporte'&&<Chat {...ctx}/>}
 </main>{me.role!=='Suporte'&&!chat&&page!=='Falar com Suporte'&&<button className="help" aria-label="Falar com Suporte" onClick={()=>setChat(true)}>?</button>}{chat&&<Modal title="Falar com Suporte" close={()=>setChat(false)}><Chat {...ctx}/></Modal>}
 {toast&&<div className="toast" role="status"><Check size={18}/>{toast}</div>}{messageNotice&&<MessageNotice names={unread.names} busy={busy} close={()=>setMessageNotice(false)} respond={()=>run(async()=>{await readMessages();setMessageNotice(false);setPage('Atendimentos')})}/>} {me.temporary&&passwordPrompt&&<ChangePassword {...ctx} close={()=>setPasswordPrompt(false)}/>} </div>;
}
function MessageNotice({names,busy,close,respond}){
 const people=names.length>2?`${names[0]}, ${names[1]} e outros`:names.length===2?`${names[0]} e ${names[1]}`:names[0];
 return <Modal title="Novas mensagens" close={close}><p>{people} {names.length===1?'enviou':'enviaram'} mensagens.</p><div className="actions"><Button className="secondary" onClick={close}>Fechar</Button><Button className="primary" busy={busy} onClick={respond}>Responder</Button></div></Modal>;
}
function AccessChoice({me,busy,run,choose}){
 const label=role=>role==='Administração'?'Administrador':role;
 return <div className="access-shell"><div className="access-choice"><h1>Escolha seu acesso</h1><div className="access-options">{me.roles.map(role=><button key={role} disabled={busy} onClick={()=>run(async()=>{const result=await api('/access',{role});choose(result.user,result.punch)})}><UserRound size={30}/><strong>Acesso de {label(role)}</strong></button>)}</div></div></div>;
}
function Login({onLogin,run,busy,notify}){
 const [login,setLogin]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState('');const lock=useRef(false);
 return <div className="login-shell"><form className="login-card" onSubmit={async e=>{e.preventDefault();if(lock.current)return;lock.current=true;try{await run(async()=>{const r=await api('/login',{login,password});onLogin(r.user,r.punch);});}finally{lock.current=false;}}}><h1>Seja bem-vindo</h1>{message&&<Notice>{message}</Notice>}<Field label="Login" autoComplete="username" value={login} onChange={e=>setLogin(e.target.value)} required autoFocus/><Password value={password} autoComplete="current-password" onChange={e=>setPassword(e.target.value)} required/><Button className="primary" busy={busy} type="submit">Entrar <ArrowRight size={18}/></Button><button type="button" className="text-button forgot" onClick={()=>run(async()=>{if(!login.trim())throw new Error('Preencha o login primeiro.');const r=await api('/recover',{login});setMessage(r.message);})}>Esqueci minha senha</button></form></div>;
}
function ChangePassword({run,busy,refresh,close}){
 const [password,setPassword]=useState(''),[repeat,setRepeat]=useState('');
 return <Modal title="Crie sua senha definitiva" close={close}><form onSubmit={e=>{e.preventDefault();run(async()=>{if(password!==repeat)throw Error('As senhas não conferem.');await api('/password',{password});await refresh();close();});}}><Password label="Nova senha" value={password} minLength={4} autoComplete="new-password" onChange={e=>setPassword(e.target.value)} required/><Password label="Confirmar nova senha" value={repeat} minLength={4} autoComplete="new-password" onChange={e=>setRepeat(e.target.value)} required/><div className="actions"><Button type="button" className="secondary" onClick={close}>Agora não</Button><Button className="primary" busy={busy}>Salvar senha</Button></div></form></Modal>;
}
function Punch({run,busy,notify,initial,onSupport}){
 const [day,setDay]=useState(initial),[clock,setClock]=useState(new Date()),[geo,setGeo]=useState(''),[question,setQuestion]=useState(null),[success,setSuccess]=useState(false),[submitting,setSubmitting]=useState(false);
 const offset=useRef(0),draft=useRef(null),lock=useRef(false);
 const load=async()=>{const d=await api('/punch/today');setDay(d);offset.current=new Date(d.now).getTime()-Date.now();};
 useEffect(()=>{if(initial){setDay(initial);offset.current=new Date(initial.now).getTime()-Date.now()}else run(load);if(initial?.location_required!==false)warmLocation();const t=setInterval(()=>{setClock(new Date(Date.now()+offset.current));},1000);const reload=setInterval(()=>{if(document.visibilityState==='visible'&&!lock.current)load().catch(()=>{});},60000);return()=>{clearInterval(t);clearInterval(reload);};},[]);
 const send=async additions=>{
   if(lock.current)return;lock.current=true;setSubmitting(true);
   try{await run(async()=>{
    if(day?.location_required!==false&&day?.geo_ready===false)throw new Error('A escola ainda precisa confirmar o local de registro. Procure a Diretoria ou o Suporte.');
    const payload={...(draft.current||{key:crypto.randomUUID()}),...additions};draft.current=payload;
    if(day?.location_required!==false&&payload.lat===undefined){try{const position=await locate();payload.lat=position.coords.latitude;payload.lon=position.coords.longitude;payload.accuracy=position.coords.accuracy;}catch(e){setGeo(e.message);return;}}
    let r;try{r=await api('/punch',payload);}catch(e){if(e.status===422){setGeo(e.message);delete payload.lat;delete payload.lon;delete payload.accuracy;return;}throw e;}
    if(r.question){setQuestion(r);return;}
    setDay(previous=>({...previous,...r.day}));setQuestion(null);setGeo('');draft.current=null;setSuccess(true);notify(r.message);setTimeout(()=>setSuccess(false),2400);
   });}finally{lock.current=false;setSubmitting(false);}
 };
 const expected=day?.periods.flat()||[],index=day?.punches.length||0,done=day&&index>=expected.length;
 return <div className="punch-area"><section className="punch-card"><div className="clock">{clock.toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'})}<span>{clock.toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo',second:'2-digit'})}</span></div><div className="next" title={expected.join(' / ')}>{day?(done?(index%2?'Saída de hora extra':expected.length?'Jornada concluída':'Grade horária incompleta'):`${index%2?'Saída':'Entrada'} · ${expected[index]} (${index+1}/${expected.length})`):'Carregando…'}</div>{day&&expected.length===0&&<div className="schedule-missing"><p>Envie seus horários pelo Falar com Suporte.</p>{onSupport&&<button className="text-button" onClick={onSupport}>Falar com Suporte</button>}</div>}<Button className={`primary punch-button ${success?'success':''}`} busy={submitting} disabled={!day||done&&index%2===0} onClick={()=>send({})}>{success?<><Check/>Ponto registrado</>:submitting?'Validando…':done&&index%2===0?'Até o próximo dia':'Registrar ponto'}</Button>{done&&index%2===0&&expected.length>0&&<button className="text-button extra-action" onClick={()=>{draft.current=null;setQuestion({question:'overtime',message:'Você está fazendo hora extra?'});}}>Registrar hora extra</button>}</section>{geo&&<section className="location-card"><MapPin/><div><h2>Verificar localização</h2><p>{geo}</p><Button busy={busy} className="secondary" onClick={()=>send({})}>Tentar novamente</Button></div></section>}{question&&<Modal title={question.message} close={()=>{setQuestion(null);draft.current=null;}}><div className="actions"><Button className="secondary" onClick={()=>{const q=question;setQuestion(null);if(q.question==='forgot')send({forgot:'no'});else draft.current=null;}}>Não</Button><Button className="primary" busy={busy} onClick={()=>{const q=question;setQuestion(null);send(q.question==='forgot'?{forgot:'yes'}:{overtime:true});}}>Sim</Button></div></Modal>}</div>;
}
createRoot(document.getElementById('root')).render(location.pathname.startsWith('/q/')?<QRAccess/>:<App/>);
