import React,{useState,useEffect} from 'react';
import {Plus,Download,Send,ChevronRight,Settings,Search} from 'lucide-react';
import {Attendance} from './people';
import {api,Field,Password,Button,Modal,Tabs,Empty,Notice,dateNow,dateLabel,hours,days,phoneFormat} from './ui';

export function Records({run,busy,notify,administrative=false,me,personId}){
 const [start,setStart]=useState(dateNow()),[end,setEnd]=useState(dateNow()),[rows,setRows]=useState([]),[expanded,setExpanded]=useState(null);
 const pid=personId||me.id,load=async()=>setRows(await api(`/records?start=${start}&end=${end}&person_id=${pid}`));useEffect(()=>{run(load)},[pid]);
 const max=Math.max(0,...rows.map(r=>r.punches.length));
 return <><form className="toolbar compact" onSubmit={e=>{e.preventDefault();run(load)}}><Field label="De" type="date" value={start} onChange={e=>setStart(e.target.value)}/><Field label="Até" type="date" value={end} onChange={e=>setEnd(e.target.value)}/><Button className="primary" busy={busy}>Consultar</Button></form><section className="sheet table-wrap"><table><thead><tr><th>Data</th>{Array.from({length:max},(_,i)=><th key={i}>{i+1}ª marcação</th>)}<th>Horas trabalhadas</th><th/></tr></thead><tbody>{rows.map(r=><React.Fragment key={r.date}><tr><td>{dateLabel(r.date)}</td>{Array.from({length:max},(_,i)=><td className="times" key={i}>{r.punches[i]?.time||'—'}</td>)}<td>{hours(r.worked)}</td><td><button className="icon" aria-label="Ver detalhes" onClick={()=>setExpanded(expanded===r.date?null:r.date)}><ChevronRight className={expanded===r.date?'open-chevron':''} size={18}/></button></td></tr>{expanded===r.date&&<tr className="detail-row"><td colSpan={max+3}><dl className="facts"><dt>Jornada</dt><dd>{r.periods.map(x=>x.join('–')).join(' / ')||'Sem expediente'}</dd><dt>Atraso</dt><dd>{hours(r.late)}</dd><dt>Hora extra</dt><dd>{hours(r.extra)}</dd><dt>Horas negativas</dt><dd>{hours(r.negative)}</dd><dt>Saldo</dt><dd>{hours(r.balance)}</dd><dt>Situação</dt><dd>{r.status}</dd></dl><RecordActions row={r} administrative={administrative||['Suporte','Diretoria'].includes(me.role)} run={run} busy={busy} notify={notify} reload={load}/></td></tr>}</React.Fragment>)}</tbody></table>{!rows.length&&<Empty/>}</section></>
}
function RecordActions({row,administrative,run,busy,notify,reload}){const [edit,setEdit]=useState(false),[times,setTimes]=useState(row.punches.map(p=>p.time)),[reason,setReason]=useState('');if(!edit)return <Button className="secondary" onClick={()=>setEdit(true)}>{administrative?'Corrigir marcações':'Solicitar correção'}</Button>;return <form onSubmit={e=>{e.preventDefault();run(async()=>{await api(administrative?'/corrections':'/requests',{person_id:row.person_id,date:row.date,times,reason,type:'point'});notify(administrative?'Marcações corrigidas':'Solicitação enviada');setEdit(false);await reload()})}}><div className="time-editor">{times.map((t,i)=><div key={i}><input type="time" aria-label={`Marcação ${i+1}`} value={t} onChange={e=>setTimes(times.map((v,j)=>i===j?e.target.value:v))}/><button type="button" className="icon" onClick={()=>setTimes(times.filter((_,j)=>j!==i))}>×</button></div>)}</div><button type="button" className="text-button" onClick={()=>setTimes([...times,''])}><Plus size={16}/>Adicionar horário</button><Field label="Motivo"><textarea value={reason} onChange={e=>setReason(e.target.value)} required/></Field><Button className="primary" busy={busy}>Salvar</Button></form>}
export function Management(ctx){const [people,setPeople]=useState([]),[search,setSearch]=useState(''),[choice,setChoice]=useState(''),[pid,setPid]=useState(''),[attendance,setAttendance]=useState(false),[events,setEvents]=useState([]);useEffect(()=>{ctx.run(async()=>{setPeople(await api('/people'));setEvents(await api('/today-events'))})},[]);const options=people.filter(p=>p.name.toLowerCase().includes(search.toLowerCase()));return <>{attendance?<><Button className="secondary" onClick={()=>setAttendance(false)}>Voltar ao histórico</Button><Attendance {...ctx} close={()=>setAttendance(false)}/></>:<><div className="management-search"><div className="search"><Search size={18}/><input placeholder="Digite o nome" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Selecionar usuário" value={choice} onChange={e=>setChoice(e.target.value)}><option value="">Selecione uma pessoa</option>{options.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><Button className="primary" disabled={!choice} onClick={()=>setPid(choice)}>Consultar</Button><Button className="secondary" onClick={()=>setAttendance(true)}>Presença do dia</Button></div>{pid?<Records {...ctx} administrative personId={pid}/>:<section className="sheet today-events"><h2>Marcações de hoje</h2>{events.map((e,i)=><p key={i}><time>{e.time}</time> — {e.name}</p>)}{!events.length&&<Empty>Nenhuma marcação hoje.</Empty>}</section>}</>}</>}

export function Requests({run,busy,notify,admin}){
 const [rows,setRows]=useState([]),[approved,setApproved]=useState(false),[name,setName]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[selected,setSelected]=useState(null),[reason,setReason]=useState('');const load=async()=>setRows(await api('/requests'));useEffect(()=>{run(load);},[]);
 const visible=rows.filter(r=>(approved?r.status==='Aprovada':r.status!=='Aprovada')&&(!name||r.name.toLowerCase().includes(name.toLowerCase()))&&(!start||r.date>=start)&&(!end||r.date<=end));return <><div className="toolbar"><Button className="secondary" onClick={()=>setApproved(!approved)}>{approved?'Voltar às pendentes':'Solicitações aprovadas'}</Button>{approved&&<><Field label="Nome" value={name} onChange={e=>setName(e.target.value)}/><Field label="De" type="date" value={start} onChange={e=>setStart(e.target.value)}/><Field label="Até" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></>}</div><section className="sheet">{!visible.length&&<Empty>Não há solicitações.</Empty>}{visible.map(r=><button key={r.id} className="list-row" onClick={()=>{setSelected(r);setReason('');}}><div><strong>{r.data.type==='point'?'Correção de ponto':'Alteração cadastral'}</strong><span>{r.name} · {dateLabel(r.date)}</span></div><span>{r.status}</span><ChevronRight size={18}/></button>)}{selected&&<Modal title="Solicitação" close={()=>setSelected(null)}><p><strong>{selected.name}</strong></p>{selected.data.type==='point'?<dl className="facts"><dt>Anterior</dt><dd>{selected.data.before.punches.map(p=>p.time).join(' · ')||'Sem marcações'}</dd><dt>Solicitado</dt><dd>{selected.data.times.join(' · ')||'Remover marcações'}</dd></dl>:<dl className="facts"><dt>Campo</dt><dd>{{name:'Nome',email:'E-mail',phone:'Telefone',birth:'Nascimento'}[selected.data.field]}</dd><dt>Anterior</dt><dd>{selected.data.before.value||'—'}</dd><dt>Solicitado</dt><dd>{selected.data.value}</dd></dl>}<p>{selected.data.reason}</p>{selected.data.decision_reason&&<Notice>{selected.status} por {selected.data.decision_by}: {selected.data.decision_reason}</Notice>}{admin&&selected.status==='Pendente'&&<><Field label="Motivo da decisão"><textarea value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="actions">{[false,true].map(approve=><Button key={String(approve)} className={approve?'primary':'secondary'} busy={busy} onClick={()=>run(async()=>{await api(`/requests/${selected.id}/decide`,{approve,reason});setSelected(null);await load();notify('Decisão registrada');})}>{approve?'Aprovar':'Reprovar'}</Button>)}</div></>}</Modal>}</section></>;
}
export function Profile({me,run,busy,notify,refresh}){
 const [edit,setEdit]=useState(false),[field,setField]=useState('name'),[value,setValue]=useState(''),[reason,setReason]=useState(''),[schedules,setSchedules]=useState([]);
 useEffect(()=>{run(async()=>setSchedules(await api(`/people/${me.id}/schedules`)));},[]);
 const direct=['Suporte','Diretoria'].includes(me.role);
 return <section className="profile-sheet sheet"><div className="profile-name"><span className="avatar large">{me.name[0]}</span><div><h2>{me.name}</h2><p>{me.role}</p></div></div><dl className="facts"><dt>E-mail</dt><dd>{me.details.email||'—'}</dd><dt>Telefone</dt><dd>{phoneFormat(me.details.phone)||'—'}</dd><dt>Nascimento</dt><dd>{dateLabel(me.details.birth)}</dd><dt>Login</dt><dd>{me.login}</dd></dl><Button className="secondary" onClick={()=>{setValue('');setEdit(true);}}>{direct?'Editar meus dados':'Solicitar alteração'}</Button>{schedules.length>0&&<details><summary>Minha jornada</summary>{schedules.filter((s,i,a)=>s.effective>=dateNow()||i===a.findIndex(x=>x.effective<=dateNow())).map(s=><div key={s.id} className="history-line"><strong>Vigência: {dateLabel(s.effective)}</strong>{Object.entries(s.days).map(([day,p])=>p.length>0&&<span key={day}>{days[day]} · {p.map(x=>x.join('–')).join(' / ')}</span>)}</div>)}</details>}{me.role==='Professor'&&<details><summary>Grade pedagógica</summary>{(me.details.lessons||[]).map((l,i)=><p key={i}>{days[l.day]} · {l.start}–{l.end} · {l.class} · {l.subject}</p>)}</details>}{edit&&<Modal title={direct?'Editar meus dados':'Solicitar alteração'} close={()=>setEdit(false)}><form onSubmit={e=>{e.preventDefault();run(async()=>{if(direct){await api('/profile',{[field]:value},'PUT');await refresh();}else await api('/requests',{type:'profile',field,value,reason});setEdit(false);notify(direct?'Dados atualizados':'Solicitação em análise');});}}><Field label="Campo"><select value={field} onChange={e=>setField(e.target.value)}>{Object.entries({name:'Nome',email:'E-mail',phone:'Telefone',birth:'Nascimento'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Novo valor" type={field==='birth'?'date':field==='email'?'email':'text'} value={field==='phone'?phoneFormat(value):value} onChange={e=>setValue(field==='phone'?e.target.value.replace(/\D/g,'').slice(0,11):e.target.value)} required/>{!direct&&<Field label="Motivo"><textarea value={reason} onChange={e=>setReason(e.target.value)} required/></Field>}<Button className="primary" busy={busy}>{direct?'Salvar':'Enviar solicitação'}</Button></form></Modal>}</section>;
}
export function Reports({me,run,busy,notify}){
 const previous=new Date();previous.setDate(1);previous.setMonth(previous.getMonth()-1);
 const [month,setMonth]=useState(previous.toISOString().slice(0,7)),[state,setState]=useState(null),[action,setAction]=useState(null),[password,setPassword]=useState(''),[reason,setReason]=useState(''),[calendar,setCalendar]=useState(false),[audit,setAudit]=useState(null);
 const load=async()=>setState(await api('/month/'+month));useEffect(()=>{run(load);},[month]);
 const download=async()=>{const blob=await api(`/month/${month}/export`,{password});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`Ponto_${month}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);await load();setAction(null);setPassword('');notify('Excel gerado');};
 return <><div className="toolbar"><Field label="Mês" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><Button className="secondary" onClick={()=>run(async()=>setAudit(await api('/audit?month='+month)))}>Ver alterações</Button></div><div className="export-area"><section className="export-card sheet"><FileIcon/><h2>Relatório Mensal de Ponto</h2>{state?.closed&&<div className="close-details"><p>Fechado por: {state.by}</p><p>Data: {new Date(state.at).toLocaleDateString('pt-BR')}</p><p>Horário: {new Date(state.at).toLocaleTimeString('pt-BR')}</p></div>}<Button className="primary" busy={busy} onClick={()=>{if(state?.closed)run(download);else{setPassword('');setAction('export');}}}><Download size={19}/>{state?.closed?'Baixar Excel':'Fechar mês e gerar Excel'}</Button>{state?.closed&&['Diretoria','Suporte'].includes(me.role)&&<button className="text-button" onClick={()=>{setPassword('');setAction('reopen');}}>Reabrir mês</button>}</section></div>{action&&<Modal title={action==='export'?'Fechar mês e gerar Excel':'Reabrir mês'} close={()=>setAction(null)}><form onSubmit={e=>{e.preventDefault();run(async()=>{if(action==='export')await download();else{await api(`/month/${month}/reopen`,{password,reason});await load();setAction(null);notify('Mês reaberto');}});}}><Password value={password} onChange={e=>setPassword(e.target.value)} required autoFocus/>{action==='reopen'&&<Field label="Motivo"><textarea value={reason} onChange={e=>setReason(e.target.value)} required/></Field>}<Button className="primary" busy={busy}>Confirmar</Button></form></Modal>}{calendar&&<Calendar run={run} busy={busy} close={()=>setCalendar(false)}/>}{audit&&<Modal title="Alterações" close={()=>setAudit(null)} wide>{!audit.length&&<Empty/>}{audit.map(a=><details key={a.id}><summary>{a.action} · {a.actor} · {new Date(a.at).toLocaleString('pt-BR')}</summary><p>{a.reason}</p><div className="audit-values"><pre>{JSON.stringify(a.before,null,2)}</pre><pre>{JSON.stringify(a.after,null,2)}</pre></div></details>)}</Modal>}</>;
}
function FileIcon(){return <div className="export-icon"><Download size={30}/></div>}
function Calendar({run,busy,close}){
 const [rows,setRows]=useState([]),[date,setDate]=useState(dateNow()),[name,setName]=useState('');const load=async()=>setRows(await api('/calendar'));useEffect(()=>{run(load);},[]);
 return <Modal title="Calendário sem expediente" close={close}><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/calendar',{date,name});setName('');await load();});}}><div className="form-grid"><Field label="Data" type="date" value={date} onChange={e=>setDate(e.target.value)} required/><Field label="Feriado / dia sem expediente" value={name} onChange={e=>setName(e.target.value)} required/></div><Button className="primary" busy={busy}>Salvar</Button></form>{rows.map(r=><div className="list-row" key={r.date}><span>{dateLabel(r.date)} · {r.name}</span><button className="text-button" onClick={()=>run(async()=>{await api('/calendar',{date:r.date,name:''});await load();})}>Remover</button></div>)}</Modal>;
}
export function Chat({me,run,busy,management=false}){
 const [rows,setRows]=useState([]),[id,setId]=useState(null),[message,setMessage]=useState(''),[closing,setClosing]=useState(false);const load=async()=>setRows(await api('/tickets'+(management?'?management=true':'')));useEffect(()=>{run(load);const timer=setInterval(()=>{if(document.visibilityState==='visible')load().catch(()=>{});},15000);return()=>clearInterval(timer);},[]);
 const selected=rows.find(r=>r.id===id)||(!management?rows[0]:null);
 return <div className="chat-layout">{management&&<div className="ticket-list">{rows.map(r=><button key={r.id} className={`list-row ${selected?.id===r.id?'active':''}`} onClick={()=>setId(r.id)}><strong>{r.name}</strong></button>)}{!rows.length&&<Empty>Não há chamados abertos.</Empty>}</div>}<div className="conversation">{selected&&<div className="chat-head"><strong>{selected.name}</strong>{management&&<button className="text-button" onClick={()=>setClosing(true)}>Concluir chamado</button>}</div>}<div className="messages">{selected?.data.messages.map((m,i)=><div key={i} className={`message ${m.support?'support-message':''}`}><strong>{m.name}</strong><p>{m.text}</p><time>{new Date(m.at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></div>)}{!selected&&<Empty>{management?'Selecione um chamado para atender.':'Como o Suporte pode ajudar?'}</Empty>}</div>{(!management||selected)&&<form className="chat-input" onSubmit={e=>{e.preventDefault();run(async()=>{await api(selected?`/tickets/${selected.id}/message`:'/tickets',{message});setMessage('');await load();});}}><textarea aria-label="Mensagem" placeholder="Escreva sua mensagem" value={message} maxLength={4000} onChange={e=>setMessage(e.target.value)} required/><Button className="primary" busy={busy} aria-label="Enviar mensagem"><Send size={19}/></Button></form>}</div>{closing&&<Modal title="Concluir chamado?" close={()=>setClosing(false)}><p>A conversa será excluída permanentemente.</p><div className="actions"><Button className="secondary" onClick={()=>setClosing(false)}>Cancelar</Button><Button className="primary" busy={busy} onClick={()=>run(async()=>{await api(`/tickets/${selected.id}`,undefined,'DELETE');setClosing(false);setId(null);await load();})}>Concluir e excluir</Button></div></Modal>}</div>;
}
export function Support({run,busy,notify,me}){
 const [tab,setTab]=useState('Ocorrências'),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[reason,setReason]=useState(''),[settings,setSettings]=useState(null),[password,setPassword]=useState(''),[completed,setCompleted]=useState(false);
 const load=async()=>setRows(await api('/support/occurrences'));useEffect(()=>{run(load);},[]);
 return <><div className="toolbar"><label className="check"><input type="checkbox" checked={completed} onChange={e=>setCompleted(e.target.checked)}/>Incluir concluídas</label><Button className="secondary" onClick={()=>run(async()=>{setSettings(await api('/support/settings'));setPassword('');})}><Settings size={18}/>Localização da escola</Button></div><section className="sheet">{rows.filter(r=>completed||r.status==='Pendente').map(r=><button key={r.id} className="list-row" onClick={()=>{setSelected(r);setReason('');}}><div><strong>{r.data.title}</strong><span>{r.name} · {dateLabel(r.date)}</span></div><span>{r.status}</span><ChevronRight size={18}/></button>)}{!rows.filter(r=>completed||r.status==='Pendente').length&&<Empty>Nenhuma ocorrência pendente.</Empty>}</section>{selected&&<Modal title={selected.data.title} close={()=>setSelected(null)}><p>{selected.name} · {dateLabel(selected.date)}</p>{selected.status==='Pendente'?<><Field label="Resultado da análise"><textarea value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="actions">{(selected.data.title==='Hora extra pendente'?[false,true]:[true]).map(approve=><Button className={approve?'primary':'secondary'} key={String(approve)} busy={busy} onClick={()=>run(async()=>{await api('/support/occurrences/'+selected.id,{approve,reason});setSelected(null);await load();notify('Análise registrada');})}>{selected.data.title==='Hora extra pendente'?(approve?'Validar extra':'Não validar'):'Concluir'}</Button>)}</div></>:<p>{selected.data.resolution}</p>}</Modal>}{settings&&<Modal title="Localização da escola" close={()=>setSettings(null)}><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/support/settings',{...settings,password},'PUT');setSettings(null);notify('Localização salva');});}}><p>Rua Vicenzo Catena, 100, Vila Remo. Confira o ponto central antes de liberar o registro real.</p><div className="form-grid">{[['lat','Latitude'],['lon','Longitude'],['accuracy','Precisão máxima (m)']].map(([key,label])=><Field key={key} label={label} type="number" step="any" value={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.value})} required/>)}</div><a href={`https://www.openstreetmap.org/?mlat=${settings.lat}&mlon=${settings.lon}#map=19/${settings.lat}/${settings.lon}`} target="_blank" rel="noreferrer">Conferir no mapa</a><label className="check"><input type="checkbox" checked={settings.verified} onChange={e=>setSettings({...settings,verified:e.target.checked})}/>Coordenadas conferidas para uso real</label><Password value={password} onChange={e=>setPassword(e.target.value)} required/><Button className="primary" busy={busy}>Salvar configuração</Button></form></Modal>}</>;
}

export function SettingsPage({run,busy,notify}){const [file,setFile]=useState(null);const save=()=>run(async()=>{const content=await new Promise((ok,no)=>{const reader=new FileReader();reader.onload=()=>ok(String(reader.result).split(',')[1]);reader.onerror=no;reader.readAsDataURL(file)});await api('/favicon',{type:file.type,content},'PUT');notify('Favicon atualizado');location.reload()});return <section className="profile-sheet sheet"><h2>Favicon do navegador</h2><p>Use JPG, JPEG ou PNG de até 500 KB.</p><input type="file" accept="image/png,image/jpeg" onChange={e=>setFile(e.target.files[0])}/><div className="actions"><Button className="secondary" onClick={()=>run(async()=>{await api('/favicon',undefined,'DELETE');location.reload()})}>Remover</Button><Button className="primary" disabled={!file} busy={busy} onClick={save}>Enviar favicon</Button></div></section>}
