import React,{useState,useEffect} from 'react';
import {Plus,Download,Send,ChevronRight,Check,Settings} from 'lucide-react';
import {api,Field,Password,Button,Modal,Tabs,Empty,Notice,dateNow,dateLabel,hours,days,phoneFormat} from './ui';

export function Records({run,busy,notify,administrative,me}){
 const [start,setStart]=useState(dateNow().slice(0,8)+'01'),[end,setEnd]=useState(dateNow()),[people,setPeople]=useState([]),[pid,setPid]=useState(''),[rows,setRows]=useState([]),[selected,setSelected]=useState(null);
 const load=async()=>setRows(await api(`/records?start=${start}&end=${end}${!administrative?'&person_id='+me.id:pid?'&person_id='+pid:''}`));
 useEffect(()=>{run(async()=>{if(administrative)setPeople(await api('/people'));await load();});},[]);
 return <><form className="toolbar" onSubmit={e=>{e.preventDefault();run(load);}}><Field label="De" type="date" value={start} onChange={e=>setStart(e.target.value)}/><Field label="Até" type="date" value={end} onChange={e=>setEnd(e.target.value)}/>{administrative&&<Field label="Pessoa"><select value={pid} onChange={e=>setPid(e.target.value)}><option value="">Todas</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>}<Button className="primary" busy={busy}>Consultar</Button></form><section className="sheet"><div className="table-wrap"><table><thead><tr><th>Data</th>{administrative&&<th>Pessoa</th>}<th>Marcações</th><th>Trabalhado</th><th>Saldo</th><th>Situação</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.person_id+':'+r.date}><td>{dateLabel(r.date)}</td>{administrative&&<td>{r.name}</td>}<td className="times">{r.punches.map(p=>p.time).join(' · ')||'—'}</td><td>{hours(r.worked)}</td><td className={r.balance<0?'negative':r.balance>0?'positive':''}>{r.balance>0?'+':''}{hours(r.balance)}</td><td>{r.status}</td><td><button className="icon" aria-label="Ver detalhes" onClick={()=>setSelected(r)}><ChevronRight size={18}/></button></td></tr>)}</tbody></table></div>{!rows.length&&<Empty/>}</section>{selected&&<RecordDetail row={selected} administrative={administrative} run={run} busy={busy} notify={notify} close={()=>{setSelected(null);run(load);}}/>}</>;
}
function RecordDetail({row:r,administrative,run,busy,notify,close}){
 const [edit,setEdit]=useState(false),[times,setTimes]=useState(r.punches.map(p=>p.time)),[reason,setReason]=useState('');
 return <Modal title={`${r.name} · ${dateLabel(r.date)}`} close={close}><dl className="facts"><dt>Jornada</dt><dd>{r.periods.map(p=>p.join('–')).join(' / ')||'Sem expediente'}</dd><dt>Total trabalhado</dt><dd>{hours(r.worked)}</dd><dt>Atraso</dt><dd>{hours(r.late)}</dd><dt>Hora extra</dt><dd>{hours(r.extra)} {r.overtime&&`· ${r.overtime}`}</dd><dt>Negativo</dt><dd>{hours(r.negative)}</dd><dt>Saldo</dt><dd>{hours(r.balance)}</dd></dl>{!edit?<><p>{r.punches.map(p=>p.time).join(' · ')||'Sem marcações'}</p><Button className="secondary" onClick={()=>setEdit(true)}>{administrative?'Corrigir ponto':'Solicitar correção'}</Button></>:<form onSubmit={e=>{e.preventDefault();run(async()=>{await api(administrative?'/corrections':'/requests',{person_id:r.person_id,date:r.date,times,reason,type:'point'});notify(administrative?'Ponto corrigido':'Solicitação enviada');close();});}}><div className="time-editor">{times.map((t,i)=><div key={i}><input aria-label={`Batida ${i+1}`} type="time" value={t} onChange={e=>setTimes(times.map((v,j)=>j===i?e.target.value:v))} required/><button type="button" className="icon" aria-label="Remover batida" onClick={()=>setTimes(times.filter((_,j)=>j!==i))}>×</button></div>)}</div><button type="button" className="text-button" onClick={()=>setTimes([...times,''])}><Plus size={16}/>Adicionar horário</button><Field label="Motivo"><textarea value={reason} onChange={e=>setReason(e.target.value)} required/></Field><Button className="primary" busy={busy}>{administrative?'Salvar correção':'Enviar solicitação'}</Button></form>}</Modal>;
}
export function Requests({run,busy,notify,admin}){
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[reason,setReason]=useState('');const load=async()=>setRows(await api('/requests'));useEffect(()=>{run(load);},[]);
 return <section className="sheet">{!rows.length&&<Empty>Não há solicitações.</Empty>}{rows.map(r=><button key={r.id} className="list-row" onClick={()=>{setSelected(r);setReason('');}}><div><strong>{r.data.type==='point'?'Correção de ponto':'Alteração cadastral'}</strong><span>{r.name} · {dateLabel(r.date)}</span></div><span>{r.status}</span><ChevronRight size={18}/></button>)}{selected&&<Modal title="Solicitação" close={()=>setSelected(null)}><p><strong>{selected.name}</strong></p>{selected.data.type==='point'?<dl className="facts"><dt>Anterior</dt><dd>{selected.data.before.punches.map(p=>p.time).join(' · ')||'Sem marcações'}</dd><dt>Solicitado</dt><dd>{selected.data.times.join(' · ')||'Remover marcações'}</dd></dl>:<dl className="facts"><dt>Campo</dt><dd>{{name:'Nome',email:'E-mail',phone:'Telefone',birth:'Nascimento'}[selected.data.field]}</dd><dt>Anterior</dt><dd>{selected.data.before.value||'—'}</dd><dt>Solicitado</dt><dd>{selected.data.value}</dd></dl>}<p>{selected.data.reason}</p>{selected.data.decision_reason&&<Notice>{selected.status} por {selected.data.decision_by}: {selected.data.decision_reason}</Notice>}{admin&&selected.status==='Pendente'&&<><Field label="Motivo da decisão"><textarea value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="actions">{[false,true].map(approve=><Button key={String(approve)} className={approve?'primary':'secondary'} busy={busy} onClick={()=>run(async()=>{await api(`/requests/${selected.id}/decide`,{approve,reason});setSelected(null);await load();notify('Decisão registrada');})}>{approve?'Aprovar':'Reprovar'}</Button>)}</div></>}</Modal>}</section>;
}
export function Profile({me,run,busy,notify,refresh}){
 const [login,setLogin]=useState(null),[reveal,setReveal]=useState(false),[password,setPassword]=useState(''),[edit,setEdit]=useState(false),[field,setField]=useState('name'),[value,setValue]=useState(''),[reason,setReason]=useState(''),[schedules,setSchedules]=useState([]);
 useEffect(()=>{run(async()=>setSchedules(await api(`/people/${me.id}/schedules`)));return()=>setLogin(null);},[]);
 const direct=['Suporte','Diretoria'].includes(me.role);
 return <section className="profile-sheet sheet"><div className="profile-name"><span className="avatar large">{me.name[0]}</span><div><h2>{me.name}</h2><p>{me.role}</p></div></div><dl className="facts"><dt>E-mail</dt><dd>{me.details.email||'—'}</dd><dt>Telefone</dt><dd>{phoneFormat(me.details.phone)||'—'}</dd><dt>Nascimento</dt><dd>{dateLabel(me.details.birth)}</dd><dt>Login</dt><dd>{login||<button className="text-button" onClick={()=>{setPassword('');setReveal(true);}}>Revelar login</button>}</dd></dl><Button className="secondary" onClick={()=>{setValue('');setEdit(true);}}>{direct?'Editar meus dados':'Solicitar alteração'}</Button>{schedules.length>0&&<details><summary>Minha jornada</summary>{schedules.map(s=><div key={s.id} className="history-line"><strong>Vigência: {dateLabel(s.effective)}</strong>{Object.entries(s.days).map(([day,p])=>p.length>0&&<span key={day}>{days[day]} · {p.map(x=>x.join('–')).join(' / ')}</span>)}</div>)}</details>}{me.role==='Professor'&&<details><summary>Grade pedagógica</summary>{(me.details.lessons||[]).map((l,i)=><p key={i}>{days[l.day]} · {l.start}–{l.end} · {l.class} · {l.subject}</p>)}</details>}{reveal&&<Modal title="Confirme sua senha" close={()=>setReveal(false)}><form onSubmit={e=>{e.preventDefault();run(async()=>{setLogin((await api('/profile/login',{password})).login);setPassword('');setReveal(false);});}}><Password value={password} onChange={e=>setPassword(e.target.value)} required autoFocus/><Button className="primary" busy={busy}>Revelar</Button></form></Modal>}{edit&&<Modal title={direct?'Editar meus dados':'Solicitar alteração'} close={()=>setEdit(false)}><form onSubmit={e=>{e.preventDefault();run(async()=>{if(direct){await api('/profile',{[field]:value},'PUT');await refresh();}else await api('/requests',{type:'profile',field,value,reason});setEdit(false);notify(direct?'Dados atualizados':'Solicitação em análise');});}}><Field label="Campo"><select value={field} onChange={e=>setField(e.target.value)}>{Object.entries({name:'Nome',email:'E-mail',phone:'Telefone',birth:'Nascimento'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Novo valor" type={field==='birth'?'date':field==='email'?'email':'text'} value={field==='phone'?phoneFormat(value):value} onChange={e=>setValue(field==='phone'?e.target.value.replace(/\D/g,'').slice(0,11):e.target.value)} required/>{!direct&&<Field label="Motivo"><textarea value={reason} onChange={e=>setReason(e.target.value)} required/></Field>}<Button className="primary" busy={busy}>{direct?'Salvar':'Enviar solicitação'}</Button></form></Modal>}</section>;
}
export function Reports({me,run,busy,notify}){
 const previous=new Date();previous.setDate(1);previous.setMonth(previous.getMonth()-1);
 const [month,setMonth]=useState(previous.toISOString().slice(0,7)),[state,setState]=useState(null),[action,setAction]=useState(null),[password,setPassword]=useState(''),[reason,setReason]=useState(''),[calendar,setCalendar]=useState(false),[audit,setAudit]=useState(null);
 const load=async()=>setState(await api('/month/'+month));useEffect(()=>{run(load);},[month]);
 const download=async()=>{const blob=await api(`/month/${month}/export`,{password});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`Ponto_${month}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);await load();setAction(null);setPassword('');notify('Excel gerado');};
 return <><div className="toolbar"><Field label="Mês" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><Button className="secondary" onClick={()=>setCalendar(true)}>Calendário sem expediente</Button><Button className="secondary" onClick={()=>run(async()=>setAudit(await api('/audit?month='+month)))}>Ver alterações</Button></div><div className="export-area"><section className="export-card sheet"><FileIcon/><h2>Relatório Mensal de Ponto</h2>{state?.closed&&<p>{state?.closed?`Fechado por ${state.by} · ${new Date(state.at).toLocaleString('pt-BR')} · versão ${state.version}`:''}</p>}<Button className="primary" busy={busy} onClick={()=>{if(state?.closed)run(download);else{setPassword('');setAction('export');}}}><Download size={19}/>{state?.closed?'Baixar Excel':'Fechar mês e gerar Excel'}</Button>{state?.closed&&['Diretoria','Suporte'].includes(me.role)&&<button className="text-button" onClick={()=>{setPassword('');setAction('reopen');}}>Reabrir mês</button>}</section></div>{action&&<Modal title={action==='export'?'Fechar mês e gerar Excel':'Reabrir mês'} close={()=>setAction(null)}><form onSubmit={e=>{e.preventDefault();run(async()=>{if(action==='export')await download();else{await api(`/month/${month}/reopen`,{password,reason});await load();setAction(null);notify('Mês reaberto');}});}}><Password value={password} onChange={e=>setPassword(e.target.value)} required autoFocus/>{action==='reopen'&&<Field label="Motivo"><textarea value={reason} onChange={e=>setReason(e.target.value)} required/></Field>}<Button className="primary" busy={busy}>Confirmar</Button></form></Modal>}{calendar&&<Calendar run={run} busy={busy} close={()=>setCalendar(false)}/>}{audit&&<Modal title="Alterações" close={()=>setAudit(null)} wide>{!audit.length&&<Empty/>}{audit.map(a=><details key={a.id}><summary>{a.action} · {a.actor} · {new Date(a.at).toLocaleString('pt-BR')}</summary><p>{a.reason}</p><div className="audit-values"><pre>{JSON.stringify(a.before,null,2)}</pre><pre>{JSON.stringify(a.after,null,2)}</pre></div></details>)}</Modal>}</>;
}
function FileIcon(){return <div className="export-icon"><Download size={30}/></div>}
function Calendar({run,busy,close}){
 const [rows,setRows]=useState([]),[date,setDate]=useState(dateNow()),[name,setName]=useState('');const load=async()=>setRows(await api('/calendar'));useEffect(()=>{run(load);},[]);
 return <Modal title="Calendário sem expediente" close={close}><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/calendar',{date,name});setName('');await load();});}}><div className="form-grid"><Field label="Data" type="date" value={date} onChange={e=>setDate(e.target.value)} required/><Field label="Feriado / dia sem expediente" value={name} onChange={e=>setName(e.target.value)} required/></div><Button className="primary" busy={busy}>Salvar</Button></form>{rows.map(r=><div className="list-row" key={r.date}><span>{dateLabel(r.date)} · {r.name}</span><button className="text-button" onClick={()=>run(async()=>{await api('/calendar',{date:r.date,name:''});await load();})}>Remover</button></div>)}</Modal>;
}
export function Chat({me,run,busy,management=false}){
 const [rows,setRows]=useState([]),[id,setId]=useState(null),[message,setMessage]=useState(''),[closing,setClosing]=useState(false);const load=async()=>setRows(await api('/tickets'+(management?'?management=true':'')));useEffect(()=>{run(load);const timer=setInterval(()=>{if(document.visibilityState==='visible')load().catch(()=>{});},15000);return()=>clearInterval(timer);},[]);
 const selected=rows.find(r=>r.id===id)||(!management?rows[0]:null);
 return <div className="chat-layout">{management&&<div className="ticket-list">{rows.map(r=><button key={r.id} className={`list-row ${selected?.id===r.id?'active':''}`} onClick={()=>setId(r.id)}><strong>{r.name}</strong></button>)}{!rows.length&&<Empty>Não há chamados abertos.</Empty>}</div>}<div className="conversation">{selected&&<div className="chat-head"><strong>{selected.name}</strong>{management&&<button className="text-button" onClick={()=>setClosing(true)}>Concluir chamado</button>}</div>}<div className="messages">{selected?.data.messages.map((m,i)=><div key={i} className={`message ${m.support?'support-message':''}`}><strong>{m.name}</strong><p>{m.text}</p><time>{new Date(m.at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></div>)}{!selected&&<Empty>{management?'Selecione um chamado para atender.':'Como o Suporte pode ajudar?'}</Empty>}</div>{(!management||selected)&&<form className="chat-input" onSubmit={e=>{e.preventDefault();run(async()=>{await api(selected?`/tickets/${selected.id}/message`:'/tickets',{message});setMessage('');await load();});}}><textarea aria-label="Mensagem" placeholder="Escreva sua mensagem" value={message} maxLength={4000} onChange={e=>setMessage(e.target.value)} required/><Button className="primary" busy={busy} aria-label="Enviar mensagem"><Send size={19}/></Button></form>}</div>{closing&&<Modal title="Concluir chamado?" close={()=>setClosing(false)}><p>A conversa será excluída permanentemente.</p><div className="actions"><Button className="secondary" onClick={()=>setClosing(false)}>Cancelar</Button><Button className="primary" busy={busy} onClick={()=>run(async()=>{await api(`/tickets/${selected.id}`,undefined,'DELETE');setClosing(false);setId(null);await load();})}>Concluir e excluir</Button></div></Modal>}</div>;
}
export function Support({run,busy,notify,me}){
 const [tab,setTab]=useState('Ocorrências'),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[reason,setReason]=useState(''),[settings,setSettings]=useState(null),[password,setPassword]=useState(''),[completed,setCompleted]=useState(false);
 const load=async()=>setRows(await api('/support/occurrences'));useEffect(()=>{run(load);},[]);
 return <><Tabs items={['Ocorrências','Atendimento']} value={tab} onChange={setTab}/>{tab==='Atendimento'?<Chat me={me} run={run} busy={busy} management/>:<><div className="toolbar"><label className="check"><input type="checkbox" checked={completed} onChange={e=>setCompleted(e.target.checked)}/>Incluir concluídas</label><Button className="secondary" onClick={()=>run(async()=>{setSettings(await api('/support/settings'));setPassword('');})}><Settings size={18}/>Localização da escola</Button></div><section className="sheet">{rows.filter(r=>completed||r.status==='Pendente').map(r=><button key={r.id} className="list-row" onClick={()=>{setSelected(r);setReason('');}}><div><strong>{r.data.title}</strong><span>{r.name} · {dateLabel(r.date)}</span></div><span>{r.status}</span><ChevronRight size={18}/></button>)}{!rows.filter(r=>completed||r.status==='Pendente').length&&<Empty>Nenhuma ocorrência pendente.</Empty>}</section></>}{selected&&<Modal title={selected.data.title} close={()=>setSelected(null)}><p>{selected.name} · {dateLabel(selected.date)}</p>{selected.status==='Pendente'?<><Field label="Resultado da análise"><textarea value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="actions">{(selected.data.title==='Hora extra pendente'?[false,true]:[true]).map(approve=><Button className={approve?'primary':'secondary'} key={String(approve)} busy={busy} onClick={()=>run(async()=>{await api('/support/occurrences/'+selected.id,{approve,reason});setSelected(null);await load();notify('Análise registrada');})}>{selected.data.title==='Hora extra pendente'?(approve?'Validar extra':'Não validar'):'Concluir'}</Button>)}</div></>:<p>{selected.data.resolution}</p>}</Modal>}{settings&&<Modal title="Localização da escola" close={()=>setSettings(null)}><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/support/settings',{...settings,password},'PUT');setSettings(null);notify('Localização salva');});}}><p>Rua Vicenzo Catena, 100, Vila Remo. Confira o ponto central antes de liberar o registro real.</p><div className="form-grid">{[['lat','Latitude'],['lon','Longitude'],['accuracy','Precisão máxima (m)']].map(([key,label])=><Field key={key} label={label} type="number" step="any" value={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.value})} required/>)}</div><a href={`https://www.openstreetmap.org/?mlat=${settings.lat}&mlon=${settings.lon}#map=19/${settings.lat}/${settings.lon}`} target="_blank" rel="noreferrer">Conferir no mapa</a><label className="check"><input type="checkbox" checked={settings.verified} onChange={e=>setSettings({...settings,verified:e.target.checked})}/>Coordenadas conferidas para uso real</label><Password value={password} onChange={e=>setPassword(e.target.value)} required/><Button className="primary" busy={busy}>Salvar configuração</Button></form></Modal>}</>;
}
