import React,{useState,useEffect} from 'react';
import {Plus,Search,ChevronRight,Trash2} from 'lucide-react';
import {api,Field,Button,Modal,Tabs,Empty,Notice,roles,days,classes,dateNow,dateLabel} from './ui';
export function People(ctx){
 const [people,setPeople]=useState([]),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[attendance,setAttendance]=useState(false),[inactive,setInactive]=useState(false);
 const load=async()=>setPeople(await api('/people'));useEffect(()=>{ctx.run(load);},[]);
 const list=people.filter(p=>(inactive||p.active)&&(p.name+' '+p.login).toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 return <><div className="toolbar"><div className="search"><Search size={19}/><input aria-label="Buscar pessoa" placeholder="Buscar pessoa" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button className="secondary" onClick={()=>setAttendance(true)}>Presença do dia</Button><Button className="primary" onClick={()=>setSelected({name:'',login:'',role:'Colaborador',hired:dateNow(),details:{}})}><Plus size={18}/>Nova pessoa</Button></div><label className="check filter-check"><input type="checkbox" checked={inactive} onChange={e=>setInactive(e.target.checked)}/>Incluir pessoas desligadas</label><section className="sheet"><div className="table-wrap"><table><thead><tr><th>Pessoa</th><th>Perfil</th><th>Login</th><th/></tr></thead><tbody>{list.map(p=><tr key={p.id}><td><div className="person"><span className="avatar">{p.name[0]}</span><div><strong>{p.name}</strong>{!p.active&&<small>Desligado em {dateLabel(p.terminated)}</small>}</div></div></td><td>{p.role}</td><td>{p.login}</td><td><button className="text-button" onClick={()=>setSelected(p)}>Abrir cadastro <ChevronRight size={16}/></button></td></tr>)}</tbody></table></div>{!list.length&&<Empty>Nenhuma pessoa encontrada.</Empty>}</section>{selected&&<PersonEditor {...ctx} person={selected} close={()=>{setSelected(null);ctx.run(load);}}/>}{attendance&&<Attendance {...ctx} close={()=>setAttendance(false)}/>}</>;
}
function PersonEditor({person,close,run,busy,notify,me}){
 const [p,setP]=useState(person),[tab,setTab]=useState('Dados'),[schedule,setSchedule]=useState({}),[effective,setEffective]=useState(dateNow()),[specific,setSpecific]=useState(false),[history,setHistory]=useState([]),[lessons,setLessons]=useState(person.details.lessons||[]),[confirmAction,setConfirmAction]=useState(null),[termination,setTermination]=useState(dateNow());
 const loadSchedules=async()=>{const rows=await api(`/people/${p.id}/schedules`);setHistory(rows);setSchedule(rows.find(r=>!r.specific)?.days||{});};
 useEffect(()=>{if(p.id)run(loadSchedules);},[p.id]);
 const detail=(key,value)=>setP({...p,details:{...p.details,[key]:value}});
 const savePerson=()=>run(async()=>{const saved=await api('/people'+(p.id?'/'+p.id:''),p,p.id?'PUT':'POST');setP(saved);notify('Cadastro salvo');});
 const pair=(day,index,part,value)=>setSchedule({...schedule,[day]:schedule[day].map((p,i)=>i===index?p.map((x,j)=>j===part?value:x):p)});
 const tabs=['Dados','Acesso','Jornada',...(p.role==='Professor'?['Grade pedagógica']:[])];
 const allowedRoles=roles.filter(r=>me.role==='Suporte'||r!=='Suporte'&&(me.role!=='Administração'||r!=='Diretoria'));
 return <Modal title={p.id?p.name:'Nova pessoa'} close={close} wide><Tabs items={tabs} value={tab} onChange={setTab}/>{tab==='Dados'&&<form onSubmit={e=>{e.preventDefault();savePerson();}}><div className="form-grid"><Field label="Nome completo" value={p.name} onChange={e=>setP({...p,name:e.target.value})} required/><Field label="Perfil"><select value={p.role} onChange={e=>setP({...p,role:e.target.value})}>{[...new Set([...allowedRoles,p.role])].map(r=><option key={r}>{r}</option>)}</select></Field><Field label="E-mail" type="email" value={p.details.email||''} onChange={e=>detail('email',e.target.value)}/><Field label="Telefone" type="tel" value={p.details.phone||''} onChange={e=>detail('phone',e.target.value)}/><Field label="Nascimento" type="date" value={p.details.birth||''} onChange={e=>detail('birth',e.target.value)}/><Field label="Admissão" type="date" value={p.hired} disabled={!!p.id} onChange={e=>setP({...p,hired:e.target.value})}/>{!p.id&&<Field label="Login" value={p.login} onChange={e=>setP({...p,login:e.target.value})} required/>}</div>{!p.id&&<p className="muted">Senha inicial: 102030. A pessoa criará uma senha no primeiro acesso.</p>}<div className="actions">{p.id&&p.active&&p.id!==me.id&&<button type="button" className="danger-text" onClick={()=>setConfirmAction('deactivate')}>Desligar pessoa</button>}<Button className="primary" busy={busy}>Salvar cadastro</Button></div></form>}
 {tab==='Acesso'&&(!p.id?<Notice>Salve os dados para configurar o acesso.</Notice>:<><Field label="Login" value={p.login} onChange={e=>setP({...p,login:e.target.value})}/><div className="actions"><Button className="secondary" onClick={()=>setConfirmAction('reset')}>Redefinir senha</Button><Button className="primary" busy={busy} onClick={savePerson}>Salvar login</Button></div></>)}
 {tab==='Jornada'&&(!p.id?<Notice>Salve os dados para cadastrar a jornada.</Notice>:<><div className="form-grid"><Field label="Válida a partir de" type="date" min={dateNow()} value={effective} onChange={e=>setEffective(e.target.value)}/><label className="check"><input type="checkbox" checked={specific} onChange={e=>setSpecific(e.target.checked)}/>Somente nessa data</label></div><div className="schedule">{days.map((name,d)=><div className="schedule-row" key={d}><strong>{name}</strong><div className="period-list">{(schedule[d]||[]).map((p,i)=><div className="period" key={i}><input aria-label={`${name} entrada ${i+1}`} type="time" value={p[0]} onChange={e=>pair(d,i,0,e.target.value)}/><span>até</span><input aria-label={`${name} saída ${i+1}`} type="time" value={p[1]} onChange={e=>pair(d,i,1,e.target.value)}/><button className="icon" aria-label="Remover período" onClick={()=>setSchedule({...schedule,[d]:schedule[d].filter((_,j)=>j!==i)})}><Trash2 size={17}/></button></div>)}</div><button className="icon add-period" aria-label={`Adicionar período ${name}`} onClick={()=>setSchedule({...schedule,[d]:[...(schedule[d]||[]),['07:00','12:00']]})}><Plus size={19}/></button></div>)}</div><div className="actions"><Button className="primary" busy={busy} onClick={()=>run(async()=>{const r=await api(`/people/${p.id}/schedules`,{days:schedule,effective,specific});notify(`Jornada salva. Vigência: ${dateLabel(r.effective)}`);await loadSchedules();})}>Salvar jornada</Button></div>{history.length>0&&<details><summary>Histórico de jornadas</summary>{history.map(h=><div className="history-line" key={h.id}><strong>{dateLabel(h.effective)}{h.specific?' · Excepcional':''}</strong>{Object.entries(h.days).filter(([,v])=>v.length).map(([d,periods])=><span key={d}>{days[d]}: {periods.map(x=>x.join('–')).join(' / ')}</span>)}</div>)}</details>}</>)}
 {tab==='Grade pedagógica'&&(!p.id?<Notice>Salve os dados para cadastrar aulas.</Notice>:<><div className="lesson-list">{lessons.map((l,i)=><div className="lesson" key={i}><Field label="Dia"><select value={l.day} onChange={e=>setLessons(lessons.map((x,j)=>j===i?{...x,day:e.target.value}:x))}>{days.map((d,n)=><option value={n} key={d}>{d}</option>)}</select></Field>{[['start','Início','time'],['end','Fim','time'],['subject','Matéria','text']].map(([key,label,type])=><Field key={key} label={label} type={type} value={l[key]} onChange={e=>setLessons(lessons.map((x,j)=>j===i?{...x,[key]:e.target.value}:x))}/>)}<Field label="Turma"><select value={l.class} onChange={e=>setLessons(lessons.map((x,j)=>j===i?{...x,class:e.target.value}:x))}>{classes.map(c=><option key={c}>{c}</option>)}</select></Field><button className="icon" aria-label="Remover aula" onClick={()=>setLessons(lessons.filter((_,j)=>j!==i))}><Trash2 size={17}/></button></div>)}</div><div className="actions"><Button className="secondary" onClick={()=>setLessons([...lessons,{day:'0',start:'07:00',end:'07:50',subject:'',class:'Jardim'}])}><Plus size={18}/>Aula</Button><Button busy={busy} className="primary" onClick={()=>run(async()=>{await api(`/people/${p.id}/lessons`,{lessons},'PUT');notify('Grade salva');})}>Salvar grade</Button></div></>)}
 {confirmAction&&<Modal title={confirmAction==='reset'?'Redefinir senha?':'Desligar pessoa?'} close={()=>setConfirmAction(null)}>{confirmAction==='reset'?<p>A senha voltará a 102030. O acesso atual será encerrado.</p>:<><p>O login será desativado. O histórico permanece disponível.</p><Field label="Último dia do vínculo" type="date" value={termination} max={dateNow()} onChange={e=>setTermination(e.target.value)}/></>}<div className="actions"><Button className="secondary" onClick={()=>setConfirmAction(null)}>Cancelar</Button><Button className="primary" busy={busy} onClick={()=>run(async()=>{await api(`/people/${p.id}/${confirmAction}`,confirmAction==='deactivate'?{date:termination}:{});notify(confirmAction==='reset'?'Senha redefinida':'Pessoa desligada');setConfirmAction(null);close();})}>Confirmar</Button></div></Modal>}
 </Modal>;
}
function Attendance({close,run,busy,notify}){
 const [day,setDay]=useState(dateNow()),[rows,setRows]=useState([]),[all,setAll]=useState(false);const load=async()=>setRows(await api('/attendance?day='+day));useEffect(()=>{run(load);},[day]);
 return <Modal title="Presença do dia" close={close} wide><div className="toolbar"><Field label="Data" type="date" value={day} onChange={e=>setDay(e.target.value)}/><label className="check"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Mostrar sem expediente</label></div><div className="table-wrap"><table><thead><tr><th>Pessoa</th><th>Jornada</th><th>Marcações</th><th>Falta</th></tr></thead><tbody>{rows.filter(r=>all||r.expected&&!r.holiday).map(r=><tr key={r.person_id}><td>{r.name}</td><td>{r.holiday||r.periods.map(p=>p.join('–')).join(' / ')||'Sem expediente'}</td><td>{r.punches.map(p=>p.time).join(' · ')||'—'}</td><td><input type="checkbox" aria-label={`Falta de ${r.name}`} checked={r.absent} disabled={busy||!r.expected||!!r.holiday} onChange={e=>run(async()=>{await api('/absence',{date:day,person_id:r.person_id,absent:e.target.checked});await load();notify('Presença atualizada');})}/></td></tr>)}</tbody></table></div>{!rows.some(r=>r.expected&&!r.holiday)&&<Empty>Não há pessoas previstas para esta data.</Empty>}</Modal>;
}
