import React,{useState,useEffect} from 'react';
import {Plus,Search,ChevronRight,Trash2,Copy,ArrowDownAZ,ArrowUpZA} from 'lucide-react';
import {api,Field,Button,Modal,Tabs,Empty,Notice,roles,days,classes,dateNow,dateLabel,phoneFormat} from './ui';
const subjectOptions=["Português", "Matemática", "Ciências", "Biologia", "Química", "Física", "História", "Geografia", "Ensino Religioso", "Prova", "Redação", "Educação Física", "Arte", "Filosofia", "Clube Robótica", "Robótica", "Bilíngue", "Sociologia", "Gramática/Inglês", "Capela", "Bilíngue/Inglês"];
let peopleCache=null,peopleRequest=null;
export const preloadPeople=()=>peopleCache?Promise.resolve(peopleCache):(peopleRequest||(peopleRequest=api('/people').then(rows=>(peopleCache=rows,peopleRequest=null,rows),error=>{peopleRequest=null;throw error})));
export function People(ctx){
 const [people,setPeople]=useState(peopleCache),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[inactive,setInactive]=useState(false),[ascending,setAscending]=useState(true);
 const load=async()=>{peopleCache=await api('/people');setPeople(peopleCache)};useEffect(()=>{if(peopleCache)setPeople(peopleCache);else ctx.run(async()=>setPeople(await preloadPeople()));},[]);
 const list=(people||[]).filter(p=>(inactive||p.active)&&(p.name+' '+p.login).toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')*(ascending?1:-1));
 return <><div className="toolbar"><div className="search"><Search size={19}/><input aria-label="Buscar usuário" placeholder="Buscar usuário" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button className="secondary" title={ascending?'Alterar para Z–A':'Alterar para A–Z'} onClick={()=>setAscending(!ascending)}>{ascending?<ArrowDownAZ size={18}/>:<ArrowUpZA size={18}/>} {ascending?'A–Z':'Z–A'}</Button><Button className="primary" onClick={()=>setSelected({name:'',login:'',role:'Colaborador',roles:['Colaborador'],hired:dateNow(),details:{}})}><Plus size={18}/>Novo usuário</Button></div><label className="check filter-check"><input type="checkbox" checked={inactive} onChange={e=>setInactive(e.target.checked)}/>Incluir usuários desligados</label><section className="sheet"><div className="table-wrap"><table><thead><tr><th>Usuário</th><th>Perfil</th><th>Login</th><th/><th className="schedule-indicator">Jornada</th></tr></thead><tbody>{list.map(p=><tr key={p.id}><td><div className="person"><span className="avatar">{p.name[0]}</span><div><strong>{p.name}</strong>{!p.active&&<small>Desligado em {dateLabel(p.terminated)}</small>}</div></div></td><td>{(p.roles||[p.role]).join(' · ')}</td><td>{p.login}</td><td><button className="text-button" onClick={()=>setSelected(p)}>Abrir cadastro <ChevronRight size={16}/></button></td><td className="schedule-indicator">{(p.roles||[p.role]).includes('Professor')&&<input type="checkbox" checked={!!p.has_schedule} disabled aria-label={`${p.name}: ${p.has_schedule?'com jornada cadastrada':'sem jornada cadastrada'}`} title={p.has_schedule?'Jornada cadastrada':'Sem jornada cadastrada'}/>}</td></tr>)}</tbody></table></div>{people!==null&&!list.length&&<Empty>Nenhum usuário encontrado.</Empty>}</section>{selected&&<PersonEditor {...ctx} person={selected} close={()=>{setSelected(null);ctx.run(load);}}/>}</>;
}
function PersonEditor({person,close,run,busy,notify,me}){
 const [p,setP]=useState(person),[tab,setTab]=useState('Dados'),[schedule,setSchedule]=useState({}),[effective,setEffective]=useState(dateNow()),[specific,setSpecific]=useState(false),[history,setHistory]=useState([]),[lessons,setLessons]=useState(person.details.lessons||[]),[subjects,setSubjects]=useState(person.details.subjects_by_class||{}),[newClass,setNewClass]=useState(classes[0]),[newSubject,setNewSubject]=useState(''),[confirmAction,setConfirmAction]=useState(null),[termination,setTermination]=useState(dateNow()),[savedSchedule,setSavedSchedule]=useState(''),[copyFrom,setCopyFrom]=useState('0'),[copyTo,setCopyTo]=useState([]),[gradeDay,setGradeDay]=useState((person.details.lessons||[])[0]?.day||'0');
 const loadSchedules=async()=>{const rows=await api(`/people/${p.id}/schedules`);setHistory(rows);setSchedule(rows.find(r=>!r.specific)?.days||{});};
 useEffect(()=>{if(p.id)run(loadSchedules);},[p.id]);
 const detail=(key,value)=>setP({...p,details:{...p.details,[key]:value}});
 const savePerson=()=>run(async()=>{const saved=await api('/people'+(p.id?'/'+p.id:''),p,p.id?'PUT':'POST');setP(saved);notify('Cadastro salvo');});
 const pair=(day,index,part,value)=>setSchedule({...schedule,[day]:schedule[day].map((p,i)=>i===index?p.map((x,j)=>j===part?value:x):p)});
 const assigned=p.roles||[p.role];
 const tabs=['Dados','Acesso','Jornada',...(assigned.includes('Professor')?['Matérias','Grade pedagógica']:[])];
 const allowedRoles=roles.filter(r=>['Suporte','Diretoria'].includes(me.role)||!['Suporte','Diretoria'].includes(r));
 const gradeClasses=Object.keys(subjects).filter(classroom=>subjects[classroom].length);
 const gradeRows=lessons.map((lesson,index)=>({lesson,index})).filter(row=>String(row.lesson.day)===String(gradeDay));
 const updateLesson=(index,values)=>setLessons(current=>current.map((lesson,i)=>i===index?{...lesson,...values}:lesson));
 return <Modal title={p.id?p.name:'Nova pessoa'} close={close} wide><Tabs items={tabs} value={tab} onChange={setTab}/>{tab==='Dados'&&<form onSubmit={e=>{e.preventDefault();savePerson();}}><div className="form-grid"><Field label="Perfil principal"><select value={p.role} onChange={e=>{const role=e.target.value;setP({...p,role,roles:[role,...assigned.filter(r=>r!==role)].slice(0,2)})}}>{[...new Set([...allowedRoles,p.role])].map(r=><option key={r}>{r}</option>)}</select></Field><Field label="Segundo acesso"><select value={assigned.find(r=>r!==p.role)||''} onChange={e=>setP({...p,roles:e.target.value?[p.role,e.target.value]:[p.role]})}><option value="">Nenhum</option>{allowedRoles.filter(r=>r!==p.role).map(r=><option key={r}>{r}</option>)}</select></Field><Field label="Nome completo" value={p.name} onChange={e=>setP({...p,name:e.target.value})} required/><Field label="E-mail" type="email" value={p.details.email||''} onChange={e=>detail('email',e.target.value)}/><Field label="Telefone" type="tel" inputMode="numeric" value={phoneFormat(p.details.phone)} onChange={e=>detail('phone',e.target.value.replace(/\D/g,'').slice(0,11))}/><Field label="Nascimento" type="date" value={p.details.birth||''} onChange={e=>detail('birth',e.target.value)}/><Field label="Admissão" type="date" value={p.hired} onChange={e=>setP({...p,hired:e.target.value})}/>{!p.id&&<Field label="Login" value={p.login} onChange={e=>setP({...p,login:e.target.value})} required/>}</div>{!p.id&&<p className="muted">Senha inicial: 102030. A pessoa criará uma senha no primeiro acesso.</p>}<div className="actions">{p.id&&p.active&&p.id!==me.id&&<button type="button" className="danger-text" onClick={()=>setConfirmAction('deactivate')}>Desligar pessoa</button>}<Button className="primary" busy={busy}>Salvar cadastro</Button></div></form>}
 {tab==='Acesso'&&(!p.id?<Notice>Salve os dados para configurar o acesso.</Notice>:<><Field label="Login" value={p.login} onChange={e=>setP({...p,login:e.target.value})}/><div className="actions">{['Suporte','Diretoria'].includes(me.role)&&<Button className="secondary" onClick={()=>setConfirmAction('reset')}>Redefinir senha</Button>}<Button className="primary" busy={busy} onClick={savePerson}>Salvar login</Button></div></>)}
 {tab==='Jornada'&&(!p.id?<Notice>Salve os dados para cadastrar a jornada.</Notice>:<><div className="form-grid"><Field label="Válida a partir de" type="date" min={dateNow()} value={effective} onChange={e=>setEffective(e.target.value)}/><label className="check"><input type="checkbox" checked={specific} onChange={e=>setSpecific(e.target.checked)}/>Somente nessa data</label></div>{savedSchedule&&<Notice>{savedSchedule}</Notice>}<div className="copy-schedule sheet"><strong>Copiar jornada de um dia</strong><Field label="Origem"><select value={copyFrom} onChange={e=>setCopyFrom(e.target.value)}>{days.map((d,i)=><option key={i} value={i}>{d}</option>)}</select></Field><div className="day-checks">{days.map((d,i)=><label className="check" key={i}><input type="checkbox" checked={copyTo.includes(String(i))} disabled={String(i)===copyFrom} onChange={e=>setCopyTo(e.target.checked?[...copyTo,String(i)]:copyTo.filter(x=>x!==String(i)))}/>{d}</label>)}</div><Button className="secondary" onClick={()=>{if(!copyTo.length)return;const next={...schedule};copyTo.forEach(d=>next[d]=(schedule[copyFrom]||[]).map(pair=>[...pair]));setSchedule(next);setSavedSchedule('Jornada copiada. Os dias selecionados foram substituídos; confirme em Salvar jornada.');}}><Copy size={17}/>Aplicar aos dias selecionados</Button></div><div className="schedule">{days.map((name,d)=><div className="schedule-row" key={d}><strong>{name}</strong><div className="period-list">{(schedule[d]||[]).map((p,i)=><div className="period" key={i}><input aria-label={`${name} entrada ${i+1}`} type="time" value={p[0]} onChange={e=>pair(d,i,0,e.target.value)}/><span>até</span><input aria-label={`${name} saída ${i+1}`} type="time" value={p[1]} onChange={e=>pair(d,i,1,e.target.value)}/><button className="icon" aria-label="Remover período" onClick={()=>setSchedule({...schedule,[d]:schedule[d].filter((_,j)=>j!==i)})}><Trash2 size={17}/></button></div>)}</div><button className="icon add-period" aria-label={`Adicionar período ${name}`} onClick={()=>setSchedule({...schedule,[d]:[...(schedule[d]||[]),['07:00','12:00']]})}><Plus size={19}/></button></div>)}</div><div className="actions"><Button className="primary" busy={busy} onClick={()=>run(async()=>{const r=await api(`/people/${p.id}/schedules`,{days:schedule,effective,specific});setEffective(r.effective);setSavedSchedule(r.deferred?`O dia já tem marcações. A nova jornada começa em ${dateLabel(r.effective)}; hoje permanece a jornada anterior.`:`Jornada salva para ${dateLabel(r.effective)}.`);notify('Jornada salva');await loadSchedules();})}>Salvar jornada</Button></div>{history.length>0&&<details><summary>Histórico de jornadas</summary>{history.map(h=><div className="history-line" key={h.id}><strong>{dateLabel(h.effective)}{h.specific?' · Excepcional':''}</strong>{Object.entries(h.days).filter(([,v])=>v.length).map(([d,periods])=><span key={d}>{days[d]}: {periods.map(x=>x.join('–')).join(' / ')}</span>)}</div>)}</details>}</>)}
 {tab==='Matérias'&&(!p.id?<Notice>Salve os dados para cadastrar matérias.</Notice>:<><div className="form-grid"><Field label="Turma"><select value={newClass} onChange={e=>setNewClass(e.target.value)}>{classes.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Matéria" list="subject-options" value={newSubject} onChange={e=>setNewSubject(e.target.value)}/><datalist id="subject-options">{subjectOptions.map(subject=><option key={subject} value={subject}/>)}</datalist></div><Button className="secondary" onClick={()=>{const value=newSubject.trim();if(!value)return;setSubjects({...subjects,[newClass]:[...new Set([...(subjects[newClass]||[]),value])]});setNewSubject('')}}><Plus size={18}/>Adicionar matéria</Button><div className="subject-groups">{Object.entries(subjects).map(([classroom,items])=><section key={classroom}><strong>{classroom}</strong>{items.map(subject=><span key={subject}>{subject}<button className="icon" aria-label={`Remover ${subject}`} onClick={()=>setSubjects({...subjects,[classroom]:items.filter(x=>x!==subject)})}>×</button></span>)}</section>)}</div><div className="actions"><Button className="primary" busy={busy} onClick={()=>run(async()=>{const r=await api(`/people/${p.id}/subjects`,{subjects},'PUT');setSubjects(r.subjects);notify('Matérias salvas')})}>Salvar matérias</Button></div></>)}
 {tab==='Grade pedagógica'&&(!p.id?<Notice>Salve os dados para cadastrar aulas.</Notice>:<>{!gradeClasses.length&&<Notice>Cadastre primeiro as matérias e suas turmas.</Notice>}<div className="grade-toolbar"><Field label="Dia da semana"><select value={gradeDay} onChange={e=>setGradeDay(e.target.value)}>{days.map((day,index)=><option value={String(index)} key={day}>{day}</option>)}</select></Field><Button className="secondary" disabled={!gradeClasses.length} onClick={()=>{const classroom=gradeClasses[0];setLessons([...lessons,{day:gradeDay,start:'07:00',end:'07:50',subject:subjects[classroom]?.[0]||'',class:classroom}])}}><Plus size={18}/>Adicionar aula</Button></div><div className="table-wrap pedagogical-table"><table><thead><tr><th>Aula</th><th>Início</th><th>Fim</th><th>Turma</th><th>Matéria</th><th/></tr></thead><tbody>{gradeRows.map(({lesson,index},position)=>{const available=subjects[lesson.class]||[];return <tr key={index}><td><strong>{position+1}ª aula</strong></td><td><input aria-label={`Início da ${position+1}ª aula`} type="time" value={lesson.start} onChange={e=>updateLesson(index,{start:e.target.value})}/></td><td><input aria-label={`Fim da ${position+1}ª aula`} type="time" value={lesson.end} onChange={e=>updateLesson(index,{end:e.target.value})}/></td><td><select aria-label={`Turma da ${position+1}ª aula`} value={lesson.class} onChange={e=>{const classroom=e.target.value;updateLesson(index,{class:classroom,subject:(subjects[classroom]||[])[0]||''})}}>{!gradeClasses.includes(lesson.class)&&<option value={lesson.class||''}>Selecione a Turma</option>}{gradeClasses.map(classroom=><option key={classroom}>{classroom}</option>)}</select></td><td><select aria-label={`Matéria da ${position+1}ª aula`} value={lesson.subject} onChange={e=>updateLesson(index,{subject:e.target.value})}>{!available.includes(lesson.subject)&&<option value={lesson.subject||''}>Selecione a Matéria</option>}{available.map(subject=><option key={subject}>{subject}</option>)}</select></td><td><button className="icon" aria-label={`Remover ${position+1}ª aula`} onClick={()=>setLessons(lessons.filter((_,i)=>i!==index))}><Trash2 size={17}/></button></td></tr>})}</tbody></table>{!gradeRows.length&&<Empty>Nenhuma aula cadastrada neste dia.</Empty>}</div><div className="actions"><Button busy={busy} className="primary" onClick={()=>run(async()=>{await api(`/people/${p.id}/lessons`,{lessons,subjects},'PUT');notify('Grade salva');})}>Salvar grade</Button></div></>)}
 {confirmAction&&<Modal title={confirmAction==='reset'?'Redefinir senha?':'Desligar pessoa?'} close={()=>setConfirmAction(null)}>{confirmAction==='reset'?<p>A senha voltará a 102030. O acesso atual será encerrado.</p>:<><p>O login será desativado. O histórico permanece disponível.</p><Field label="Último dia do vínculo" type="date" value={termination} max={dateNow()} onChange={e=>setTermination(e.target.value)}/></>}<div className="actions"><Button className="secondary" onClick={()=>setConfirmAction(null)}>Cancelar</Button><Button className="primary" busy={busy} onClick={()=>run(async()=>{await api(`/people/${p.id}/${confirmAction}`,confirmAction==='deactivate'?{date:termination}:{});notify(confirmAction==='reset'?'Senha redefinida':'Pessoa desligada');setConfirmAction(null);close();})}>Confirmar</Button></div></Modal>}
 </Modal>;
}
export function Attendance({close,run,busy,notify}){
 const [day,setDay]=useState(dateNow()),[rows,setRows]=useState([]),[all,setAll]=useState(false);const load=async()=>setRows(await api('/attendance?day='+day));useEffect(()=>{run(load);},[day]);
 return <Modal title="Presença do dia" close={close} wide><div className="toolbar"><Field label="Data" type="date" value={day} onChange={e=>setDay(e.target.value)}/><label className="check"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Mostrar sem expediente</label></div><div className="table-wrap"><table><thead><tr><th>Pessoa</th><th>Jornada</th><th>Marcações</th><th>Falta</th></tr></thead><tbody>{rows.filter(r=>all||r.expected&&!r.holiday).map(r=><tr key={r.person_id}><td>{r.name}</td><td>{r.holiday||r.periods.map(p=>p.join('–')).join(' / ')||'Sem expediente'}</td><td>{r.punches.map(p=>p.time).join(' · ')||'—'}</td><td><input type="checkbox" aria-label={`Falta de ${r.name}`} checked={r.absent} disabled={busy||!r.expected||!!r.holiday} onChange={e=>run(async()=>{await api('/absence',{date:day,person_id:r.person_id,absent:e.target.checked});await load();notify('Presença atualizada');})}/></td></tr>)}</tbody></table></div>{!rows.some(r=>r.expected&&!r.holiday)&&<Empty>Não há pessoas previstas para esta data.</Empty>}</Modal>;
}
