import React,{useEffect,useRef,useState} from 'react';
import {api,Button} from './ui';import {locate} from './location';
export function QRAccess(){
 const token=decodeURIComponent(location.pathname.slice(3)),[state,setState]=useState(null),[clock,setClock]=useState(new Date()),[error,setError]=useState(''),[busy,setBusy]=useState(false),[question,setQuestion]=useState(null),[done,setDone]=useState(null);const draft=useRef(null),lock=useRef(false),offset=useRef(0);
 const load=async()=>{try{const data=await api('/qr/'+token);setState(data);offset.current=new Date(data.now).getTime()-Date.now();}catch(e){setError(e.message)}};
 useEffect(()=>{load();const timer=setInterval(()=>setClock(new Date(Date.now()+offset.current)),1000);return()=>clearInterval(timer)},[]);
 const send=async extra=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const position=await locate(),payload={...(draft.current||{key:crypto.randomUUID()}),...extra,lat:position.coords.latitude,lon:position.coords.longitude,accuracy:position.coords.accuracy};draft.current=payload;const result=await api('/qr/'+token+'/punch',payload);if(result.question){setQuestion(result);return}setDone(result);draft.current=null;setTimeout(()=>{window.close();setTimeout(()=>{if(history.length>1)history.back()},150)},3000)}catch(e){setError(e.message)}finally{setBusy(false);lock.current=false}};
 if(done)return <main className="qr-success"><time>{done.registered_at}</time><h1>{done.confirmation}</h1><p>Pode fechar esta página</p></main>;
 return <main className="qr-access">{state?<><h1>Olá, {state.name}</h1><div className="qr-clock">{clock.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}<small>{clock.toLocaleTimeString('pt-BR',{second:'2-digit'})}</small></div><Button className="primary qr-button" busy={busy} disabled={!state.can_register} onClick={()=>send({})}>{state.next}</Button>{error&&<p className="inline-error">{error}</p>}{question&&<div className="qr-question"><p>{question.message}</p><Button className="secondary" onClick={()=>send({forgot:'no'})}>Não</Button><Button className="primary" onClick={()=>send(question.question==='forgot'?{forgot:'yes'}:{overtime:true})}>Sim</Button></div>}</>:<p>{error||'Carregando…'}</p>}</main>
}
